[project]
name = "session-class"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jahanzaib Tayyab", email = "jtayyab204@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "greenlet>=3.2.4",
    "openai-agents[sqlalchemy]>=0.4.2",
    "psycopg2>=2.9.11",
    "python-dotenv>=1.2.1",
    "rich>=14.2.0",
]

[project.scripts]
session-class = "session_class:main"
session-pg="session_class.pg_session:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
